### ISSUE TITLE
How to modify the default width of the pop-up window?

### ISSUE THREAD

**Issue by andrew-zyf** [afadingthought/kiki-ai-workflow#6]
<img width="420" alt="image" src="https://github.com/user-attachments/assets/ef2ad1a4-cd57-4b76-909b-29d847a40dbf">

By default, the pop-up window has a relatively narrow width.

**Comment by ognistik** [comment]
Hi! Unfortunately, this seems to be a limitation of Applescript Dialogs (which Kiki uses). The only way to make them wider, is by adding blank spaces o the buttons, but it looks quite a bit strange:
![CleanShot 2024-08-09 at 15 41 03@2x](https://github.com/user-attachments/assets/24657931-34d6-4024-ae62-3ea718e005c7)

The only solution, it seems, is to use something that is not Applescript Dialogs, but I haven't spent enough time researching what to use or how to deal with that. I was considering using Alfred's new text view, but it seems it's not possible to pin the window on top of other windows all the time, as with AppleScript dialogs, and this is a feature I really like and use a lot with Kiki. My current solution for extended conversations using Kiki—chats that require a lot of output—is to use the Markdown chat feature. When I have a chance I'll try to look more into this and see if there's an app or something that will allow me show stay-on-top dialogs I can customize better.

**Comment by andrew-zyf** [comment]
I understand. Thank you very much for the ideas you provided. Where in which code file can I find the "The only way to make them wider, is by adding blank spaces o the buttons" that you mentioned? I'll try to modify it.

**Comment by ognistik** [comment]
I have modified the workflow to create the dialogs through an external script. This should make it easier for you to edit. The main dialog for conversations is in [THIS AREA](https://github.com/ognistik/kiki-ai-workflow/blob/ae5358f1fe128704186115e8b923d0f7ef4bd865/Workflow/scripts/dialog-chat.js#L19). Where it says:
```
buttons {"Close", "Copy & Close", "Continue"}
```
you need to make them
```
buttons {"-     Close     -", "-     Copy & Close     -", "-     Continue     -"}
```

But watch out, because every time these buttons are mentioned they need to be modified the same:

```
...cancel button "-     Close     -" with...
...if button returned of userResponse is "-     Continue     -" then...
...else if button returned of userResponse is "-     Copy & Close     -" then...
```

Another part where there's an Applescript dialog is if you want to resume the conversation from context file. [THIS IS the file](https://github.com/ognistik/kiki-ai-workflow/blob/ae5358f1fe128704186115e8b923d0f7ef4bd865/Workflow/scripts/resume-chat.js#L44). And finally, there's one for Whisper transcriptions [HERE](https://github.com/ognistik/kiki-ai-workflow/blob/ae5358f1fe128704186115e8b923d0f7ef4bd865/Workflow/scripts/whisper-dialog.js#L15).

In all three cases you may also find something like this:
```
if (fileContents.length > 1800) {
  fileContents = fileContents.substring(0, 1800) + "...\n\n(Response truncated. Don't worry, your conversation is intact. You may reply back or copy.)";
}
```
which cuts off the message if it's too long. You may need to modify it since you will have space for longer answers.

Hope this helps!
